name = "inplus"
compatibility_date = "2026-08-27"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "inplus-db"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
preview_database_id = "REPLACE_WITH_D1_DATABASE_ID"
